EXO-60659: migration page Addon management to new documentation site
exoplatform/exoplatform.github.io pull request #14
Opened 2022-11-04 11:43 UTC by ahamdi

Migrate documentation from https://docs.exoplatform.org/en/6.3/eXo_addons.html

2022-11-09 15:03 UTC, rdenarie requested changes

2022-11-09 15:03 UTC, rdenarie commented on docs/administration/addons-management.md
> + The easiest way to manage add-ons is to use the eXo Add-ons Manager that is shipped by default in all 4.3 editions. The eXo Add-ons Manager defines a standard approach of packaging, installing/unins
```suggestion
 The easiest way to manage add-ons is to use the eXo Add-ons Manager that is shipped by default in all versions superior to 4.3. The eXo Add-ons Manager defines a standard approach of packaging, installing/uninstalling and updating the available add-ons. With the eXo Add-ons Manager, you, as administrators, can enhance your management of the add-ons installed on the eXo Platform instances via the Command Line Interface (known as CLI), in a simple manner.
```

2022-11-14 14:37 UTC, ahamdi commented
@rdenarie PR updated

2022-11-15 15:34 UTC, rdenarie approved these changes

2022-11-15 17:02 UTC, merged